/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author march
 */
public class CreditoViviendaView extends javax.swing.JPanel {

    /**
     * Creates new form CreditoViviendaView
     */
    public CreditoViviendaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtIngresoFamiliar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbSi);
        rbSi.setText("Si");
        add(rbSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        buttonGroup1.add(rbNo);
        rbNo.setText("No");
        add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel1.setText("Ingreso Familiar:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        add(txtIngresoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 250, 30));

        jLabel2.setText("Vivienda:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton rbNo;
    public javax.swing.JRadioButton rbSi;
    public javax.swing.JTextField txtIngresoFamiliar;
    // End of variables declaration//GEN-END:variables
}
